"""add version column for optimistic concurrency

Revision ID: 88f64bd1a65c
Revises: cf2177033d8a
Create Date: 2026-09-18 19:41:52.160172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f64bd1a65c'
down_revision: Union[str, None] = 'cf2177033d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('tasks', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version')
    op.drop_column('projects', 'version')
    # ### end Alembic commands ###
